### ISSUE TITLE
Cannot create mock dataset

### ISSUE THREAD

**Issue by wolny** [Bayer-Group/pado#27]
Hi, I was trying to create the mock dataset based on the example in the readme, but get the following error:

```
from pado.mock import mock_dataset
ds = mock_dataset(None)

Traceback (most recent call last):
  File "/Users/adrianwolny/workspace/pado/pado/demo.py", line 2, in <module>
    ds = mock_dataset(None)
  File "/Users/adrianwolny/workspace/pado/pado/mock.py", line 98, in mock_dataset
    ip = mock_images(images_urlpath, num_images)
  File "/Users/adrianwolny/workspace/pado/pado/mock.py", line 206, in mock_images
    image = Image(
  File "/Users/adrianwolny/workspace/pado/pado/images/image.py", line 151, in __init__
    self._metadata = self._load_metadata()
  File "/Users/adrianwolny/workspace/pado/pado/images/image.py", line 338, in _load_metadata
    return ImageMetadata(
  File "/Users/adrianwolny/miniconda3/envs/pasu/lib/python3.9/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ImageMetadata
objective_power
  Input should be a valid string [type=string_type, input_value=40, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
```

Is there a way to disable the `pydantic` validation to make it work?

**Comment by ap--** [comment]
Probably same issue as #26 

try:

```shell
python3.10 -m venv venv310
source venv310/bin/activate
pip install pado"[cli,create]" \
  git+https://github.com/bayer-science-for-a-better-life/pathdrive-pado-tggates \
  rich pydantic"<2"

```

**Comment by wolny** [comment]
thanks for info @ap--, it indeed works after downgrading to `pydantic v1.10+`
